### PR TITLE
Fix errors detected by GolangCI

### LINKED ISSUE #11: Integrate linter from GolangCI
- [x] Use https://golangci.com
- [ ] Fix all found errors

### PR DESCRIPTION
**Pull request by pkosiec**
Resolves #11

### CODE REVIEW

File: pkg/recipe/recipe.go [hunk 1]
```diff
@@ -82,7 +83,12 @@ func FromURL(url string, httpClient HTTPClient) (*Recipe, int, error) {
 	if err != nil {
 		return nil, 0, errors.Wrapf(err, "while requesting recipe from URL %s", url)
 	}
-	defer res.Body.Close()
+	defer func() {
+		err = res.Body.Close()
+		if err != nil {
+			log.Printf(errors.Wrapf(err, "while closing response body").Error())
```
Comment (golangcibot) [inline pkg/recipe/recipe.go]: SA1006: printf-style function with dynamic first argument and no further arguments should use print-style function instead (from `staticcheck`)

File: pkg/shell/shell.go [hunk 2]
```diff
@@ -134,3 +135,10 @@ func (s *shell) isCommandAvailable(cmdName string) bool {
 
 	return true
 }
+
+func logErrorIfOccurred(fn func() error, context string) {
+	err := fn()
+	if err != nil {
+		log.Printf(errors.Wrapf(err, context).Error())
```
Comment (golangcibot) [inline pkg/shell/shell.go]: SA1006: printf-style function with dynamic first argument and no further arguments should use print-style function instead (from `staticcheck`)
